version: '3.8'

services:
  app:
    image: spring-boot-api:latest
    ports:
      - "80:8080"
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ar_book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: